version: "3.7"

services:
  fastapi-app:
    build:
      context: ./fastapi-app      # Dockerfile이 위치한 디렉토리 경로
      dockerfile: Dockerfile      # Dockerfile 이름 (생략 가능, 기본값은 'Dockerfile')
    container_name: FastApi-app
    ports:
      - "5002:8000"
    networks:
      - loadtest-net

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true  # 메모리 제한 환경에서 유용한 옵션
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - loadtest-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "7070:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - loadtest-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # admin은 기본 Grafana 로그인 비밀번호(변경된 비밀번호로 수정 권장)
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
      - GF_ANALYTICS_CHECK_FOR_PLUGIN_UPDATES=false
      - GF_PLUGINS_PREINSTALL_AUTO_UPDATE=false
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - loadtest-net

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "7100:9100"
    networks:
      - loadtest-net

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  grafana-data:

networks:
  loadtest-net:
    external: true
    name: fastapi_todos_loadtest-net
