# ???? ?? ??
sonar.projectKey=fastapi_app
sonar.projectName=FastAPI App
sonar.projectVersion=1.0

# ?? ?? ?? (??? ?? ?? ?? ?? ??)
sonar.sources=.

# SonarQube ?? URL (docker-compose? ?? ?? SonarQube? ??)
sonar.host.url=http://localhost:9000

# ?? ?? (??? ???? ???? ??? ??? ??)
sonar.python.coverage.reportPaths=coverage.xml

# html 내부의 js 코드도 분석에서 제외
sonar.exclusions=**/*.js,**/*.css,**/*.html

# 테스트 파일은 커버리지 측정 대상에서 제외 (테스트 코드 자체의 커버리지는 의미 없음)
sonar.coverage.exclusions=**/tests/**